CREATE DATABASE Cadastro_Cliente;

USE Cadastro_Cliente;

CREATE TABLE Cliente (
	COD INT NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	NASCIMENTO DATETIME NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL);

ALTER TABLE Cliente 
ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (COD);

GRANT execute,select,insert,update,delete TO public
